<a href="https://colab.research.google.com/github/rekuantsun/CTDL-GT/blob/main/ma_di_tuan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Bài toán mã đi tuần**

- Mã đi tuần (hay hành trình của quân mã) là bài toán về việc di chuyển một quân mã trên bàn cờ vua (8 x 8). Quân mã được đặt ở một ô trên một bàn cờ trống nó phải di chuyển theo quy tắc của cờ vua để đi qua mỗi ô trên bàn cờ đúng một lần.

- Nếu một quân mã đi hết 64 vị trí và tại vị trí cuối cùng có thể di chuyển đến vị trí bắt đầu thông qua một nước cờ thì đó gọi là một hành trình đóng.

- Có những hành trình, trong đó quân mã sau khi đi hết tất cả 64 ô của bàn cờ và từ ô cuối của hành trình không thể đi về ô xuất phát chỉ bằng một nước đi. Những hành trình như vậy được gọi là hành trình mở.

In [1]:
import numpy as np

# Các nước có thể đi tương ứng
X = [-2,-2,-1,-1, 1, 1, 2, 2]
Y = [-1, 1,-2, 2,-2, 2,-1, 1]

# Khởi tạo bàn cờ vua n x n:
def init(n):
    return np.zeros((n,n), dtype = int)

# Hàm di chuyển vị trí phù hợp
# input:  Ma trận A(bàn cờ), n: số chiều của ma trận A,
# x, y : Tọa độ của điểm
# count: Số bước đi
count = 0

def move(A,n,x,y,count):
    # Khởi tạo số bước đi
    count += 1
    A[x][y] = count
    for i in range(8):
        # Kiểm tra đã đi hết bàn cờ chưa
        if (count == n**2):
            print("Cách đi là: ")
            print(A)
            quit()
        # Tạo bước mới khi chưa đi hết bàn cờ:
        a = x + X[i]
        b = y + Y[i]
        # Kiểm tra có vị trí chuẩn bị đi có hợp lệ không
        if (a >= 0 and a < n and b >= 0 and b < n and A[a][b] == 0):
            move(A,n,a,b,count)
    # Nếu không tìm được bước đi thì trả lại:
    count -= 1
    A[x][y] = 0

def main():
    n = int(input("Nhập kích thước bàn cờ vua: "))
    A = init(n)
    print("Nhập vị trí ban đầu")
    x = int(input("Nhập x = "))
    y = int(input("Nhập y = "))
    move(A,n,x,y,count)
    print("Không tìm thấy đường đi")

if __name__ == "__main__":
    main()

Kết quả truyền trực tuyến bị cắt bớt đến 5000 dòng cuối.
 [ 3 16 11  6 25]]
Cách đi là: 
[[ 1 14 19  8 23]
 [20  9 22 13 18]
 [15  2  7 24  5]
 [10 21  4 17 12]
 [ 3 16 11  6 25]]
Cách đi là: 
[[ 1 18  9 12 23]
 [ 8 13 22 17 10]
 [19  2 11 24  5]
 [14  7  4 21 16]
 [ 3 20 15  6 25]]
Cách đi là: 
[[ 1 18  9 12 23]
 [ 8 13 22 17 10]
 [19  2 11 24  5]
 [14  7  4 21 16]
 [ 3 20 15  6 25]]
Cách đi là: 
[[ 1 18  9 12 23]
 [ 8 13 22 17 10]
 [19  2 11 24  5]
 [14  7  4 21 16]
 [ 3 20 15  6 25]]
Cách đi là: 
[[ 1 18  9 12 23]
 [ 8 13 22 17 10]
 [19  2 11 24  5]
 [14  7  4 21 16]
 [ 3 20 15  6 25]]
Cách đi là: 
[[ 1 18  9 12 23]
 [ 8 13 22 17 10]
 [19  2 11 24  5]
 [14  7  4 21 16]
 [ 3 20 15  6 25]]
Cách đi là: 
[[ 1 18  9 12 23]
 [ 8 13 22 17 10]
 [19  2 11 24  5]
 [14  7  4 21 16]
 [ 3 20 15  6 25]]
Cách đi là: 
[[ 1 18  9 12 23]
 [ 8 13 22 17 10]
 [19  2 11 24  5]
 [14  7  4 21 16]
 [ 3 20 15  6 25]]
Cách đi là: 
[[ 1 18  9 12 23]
 [ 8 13 22 17 10]
 [19  2 11 24  5]
 [14  7  4 21 16]
 [ 3 20